// High Guard Update 2022 + 코어 룰북 KR 2020 기반 우주선 데이터 (한글화)

export const SHIP_DATA = {

  // =============================================
  // 소형정 (Small Craft)
  // =============================================

  "ultralight-fighter": {
    name: "초경량 전투기",
    type: "소형정",
    hull: 6,
    hullShape: "유선형",
    armor: 3,
    armorType: "수정철",
    maneuver: 6,
    jump: 0,
    power: 15,
    fuel: 1,
    bridge: "조종석",
    computer: "컴퓨터/5",
    sensors: "민간용",
    weapons: "고정 마운트(펄스 레이저) ×1",
    crew: "조종사",
    staterooms: "없음",
    cargo: 0.06,
    tl: 12,
    durability: 2,
    maintenance: "Cr528/월",
    price: "MCr6.3324",
    powerReq: { core: 2, maneuver: 4, sensors: 1, weapons: 3 },
    notes: "4기가 30톤 전투기 프레임 모듈에 탑재되어 운용. 열등한 적에 대응하기 위한 저비용 전투기. 스텔스(향상) 탑재."
  },

  "light-fighter": {
    name: "경량 전투기",
    type: "소형정",
    hull: 10,
    hullShape: "유선형",
    armor: 2,
    armorType: "수정철",
    maneuver: 6,
    jump: 0,
    power: 15,
    fuel: 1,
    bridge: "조종석",
    computer: "컴퓨터/5",
    sensors: "개선형",
    weapons: "고정 마운트(펄스 레이저) ×1",
    crew: "조종사",
    staterooms: "없음",
    cargo: 1.7,
    tl: 12,
    durability: 4,
    maintenance: "Cr786/월",
    price: "MCr9.432",
    powerReq: { core: 2, maneuver: 6, sensors: 4, weapons: 3 },
    notes: "소형·고기동 전투기. 적 함선 고속 공격 및 소형정 격파 전문. 저예산으로 방어 가능한 세계를 위한 설계."
  },

  "heavy-fighter": {
    name: "중량 전투기",
    type: "소형정",
    hull: 50,
    hullShape: "유선형",
    armor: 15,
    armorType: "결합 초고밀도",
    maneuver: 9,
    jump: 0,
    power: 70,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/35",
    sensors: "고급형",
    weapons: "단일 포탑(빔 레이저) ×1 / 고정 마운트(미사일 발사대) ×1",
    crew: "조종사, 포격수",
    staterooms: "일반 객실 ×2",
    cargo: 0.95,
    tl: 15,
    durability: 22,
    maintenance: "Cr5743/월",
    price: "MCr68.913",
    powerReq: { core: 10, maneuver: 45, sensors: 6, weapons: 4 },
    notes: "TL15 최상위 전투기. 장갑 15, 미사일 60발 탑재. 장갑 격벽으로 주요 시스템 보호. 함대 전투 지원용."
  },

  "military-gig": {
    name: "군용 소형정",
    type: "소형정",
    hull: 20,
    hullShape: "유선형",
    armor: 4,
    armorType: "결합 초고밀도",
    maneuver: 8,
    jump: 0,
    power: 30,
    fuel: 1,
    bridge: "홀로그래픽 조종석",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(펄스 레이저, 집중 초점, 고출력) ×1",
    crew: "조종사, 포격수",
    staterooms: "비상 저온 침상 ×3",
    cargo: 2.1,
    tl: 14,
    durability: 8,
    maintenance: "Cr1139/월",
    price: "MCr13.6683",
    powerReq: { core: 4, maneuver: 16, weapons: 3, lowBerths: 3 },
    notes: "가제트급 근접 호위함 탑재 소형정. 고성능 기동력과 무장으로 도주 선박 추격. 스텔스(향상) 탑재."
  },

  "launch": {
    name: "런치",
    type: "소형정",
    hull: 20,
    hullShape: "유선형",
    armor: 0,
    maneuver: 1,
    jump: 0,
    power: 10,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "없음",
    crew: "조종사",
    staterooms: "없음",
    cargo: 14.8,
    tl: 12,
    durability: 8,
    maintenance: "Cr197/월",
    price: "MCr2.367",
    powerReq: { core: 4, maneuver: 2 },
    notes: "구명정이라고도 불림. 다목적 활용 가능한 저비용 소형정. 20톤 선체로 단독 운항 가능."
  },

  "ships-boat": {
    name: "함재정",
    type: "소형정",
    hull: 30,
    hullShape: "유선형",
    armor: 0,
    maneuver: 5,
    jump: 0,
    power: 23,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "캐빈 ×6",
    cargo: 12,
    tl: 12,
    durability: 12,
    maintenance: "Cr569/월",
    price: "MCr6.822",
    powerReq: { core: 6, maneuver: 15 },
    notes: "가장 일반적인 함재 보조정. 빠르고 다목적. 소화물·승객 수송에 주로 사용."
  },

  "slow-boat": {
    name: "저속 함재정",
    type: "소형정",
    hull: 30,
    hullShape: "유선형",
    armor: 0,
    maneuver: 3,
    jump: 0,
    power: 15,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "캐빈 ×2",
    cargo: 19.1,
    tl: 12,
    durability: 12,
    maintenance: "Cr419/월",
    price: "MCr5.022",
    powerReq: { core: 6, maneuver: 9 },
    notes: "함재정의 저성능·저비용 변형. 속도를 희생하고 화물 공간 확장."
  },

  "pinnace": {
    name: "피나스",
    type: "소형정",
    hull: 40,
    hullShape: "유선형",
    armor: 0,
    maneuver: 5,
    jump: 0,
    power: 40,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "캐빈 ×6",
    cargo: 21,
    tl: 12,
    durability: 16,
    maintenance: "Cr726/월",
    price: "MCr8.712",
    powerReq: { core: 8, maneuver: 20 },
    notes: "속도·항속거리·화물 적재량을 균형 있게 갖춘 보조정. 장거리 임무 지원에 적합."
  },

  "slow-pinnace": {
    name: "저속 피나스",
    type: "소형정",
    hull: 40,
    hullShape: "유선형",
    armor: 0,
    maneuver: 3,
    jump: 0,
    power: 20,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "없음",
    cargo: 30.8,
    tl: 8,
    durability: 16,
    maintenance: "Cr497/월",
    price: "MCr5.967",
    powerReq: { core: 8, maneuver: 9 },
    notes: "피나스의 저속·화물 특화 변형. 속도를 희생하고 화물 공간을 최대화."
  },

  "modular-cutter": {
    name: "모듈식 커터",
    type: "소형정",
    hull: 50,
    hullShape: "유선형",
    armor: 0,
    maneuver: 4,
    jump: 0,
    power: 30,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "캐빈 ×4",
    cargo: 4,
    tl: 12,
    durability: 20,
    maintenance: "Cr895/월",
    price: "MCr10.737",
    powerReq: { core: 10, maneuver: 20 },
    notes: "30톤 탈착식 모듈 탑재. 역할 전환 가능: 병력 수송·연료 채집·전투기 프레임·화물 운반 등 모듈 교체로 용도 변경."
  },

  "torpedo-boat": {
    name: "어뢰정",
    type: "소형정",
    hull: 70,
    hullShape: "유선형",
    armor: 12,
    armorType: "수정철",
    maneuver: 6,
    jump: 0,
    power: 66,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/20",
    sensors: "개선형",
    weapons: "어뢰 발사대 ×1",
    crew: "조종사, 포격수",
    staterooms: "일반 객실 ×1",
    cargo: 1.6,
    tl: 12,
    durability: 30,
    maintenance: "Cr3451/월",
    price: "MCr41.4072",
    powerReq: { core: 14, maneuver: 42, sensors: 4, weapons: 2 },
    notes: "어뢰 30발 탑재. 소형·고기동으로 대형함에 치명타. 분대 운용 시 대형 함선에도 큰 위협."
  },

  "troop-transport": {
    name: "병력 수송정",
    type: "소형정",
    hull: 50,
    hullShape: "유선형",
    armor: 5,
    armorType: "결합 초고밀도",
    maneuver: 9,
    jump: 0,
    power: 60,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/25",
    sensors: "개선형",
    weapons: "단일 포탑(샌드캐스터) ×1 / 고정 마운트(미사일 발사대) ×1",
    crew: "조종사, 포격수",
    staterooms: "가속 좌석 ×50",
    cargo: 1.7,
    tl: 15,
    durability: 22,
    maintenance: "Cr3788/월",
    price: "MCr45.45",
    powerReq: { core: 10, maneuver: 45, sensors: 4, weapons: 1 },
    notes: "제국 해군 병력 궤도-지상 투하 전용. 50명 탑승. 50톤 사출관 배치 가능. 스텔스(향상) 탑재."
  },

  "shuttle": {
    name: "셔틀",
    type: "소형정",
    hull: 95,
    hullShape: "유선형",
    armor: 0,
    maneuver: 3,
    jump: 0,
    power: 48,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "기본형",
    weapons: "고정 마운트(비어 있음) ×1",
    crew: "조종사",
    staterooms: "캐빈 ×8",
    cargo: 63.4,
    tl: 12,
    durability: 38,
    maintenance: "Cr1223/월",
    price: "MCr14.6745",
    powerReq: { core: 19, maneuver: 29 },
    notes: "궤도 운용의 표준 함재정. 항공익 탑재로 대기권 비행 가능. 화물·승객 수송의 핵심."
  },

  "passenger-shuttle": {
    name: "여객 셔틀",
    type: "소형정",
    hull: 95,
    hullShape: "유선형",
    armor: 0,
    maneuver: 1,
    jump: 0,
    power: 30,
    fuel: 1,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "민간용",
    weapons: "없음",
    crew: "조종사 ×2",
    staterooms: "가속 벤치 ×60",
    cargo: 12.3,
    tl: 9,
    durability: 38,
    maintenance: "Cr1073/월",
    price: "MCr12.8745",
    powerReq: { core: 19, maneuver: 10, sensors: 1 },
    notes: "단거리 대량 여객 수송 전용. 최대 240명 탑승. 항공익 탑재 대기권 비행 가능."
  },

  "jump-shuttle": {
    name: "점프 셔틀",
    type: "소형정",
    hull: 200,
    hullShape: "일반형",
    armor: 0,
    maneuver: 3,
    jump: 3,
    power: 105,
    fuel: 115,
    bridge: "소형 브리지",
    computer: "컴퓨터/10bis",
    sensors: "민간용",
    weapons: "없음",
    crew: "조종사, 항법사, 기관사",
    staterooms: "이인실 ×2",
    cargo: 2,
    tl: 13,
    durability: 80,
    maintenance: "Cr5580/월",
    price: "MCr66.951",
    powerReq: { core: 40, maneuver: 60, jump: 60, sensors: 1, fuelProcessor: 3 },
    fuelConsumption: { jump3: 120 },
    notes: "점프 불가 함선(SDB 등) 이송 전용. 도킹 클램프 탑재. 연료 2회 연속 점프 분량 탑재."
  },

  // =============================================
  // 탐사선
  // =============================================

  "scout": {
    name: "정찰선/연락선 (수리만급)",
    type: "탐사선",
    hull: 100,
    hullShape: "유선형",
    armor: 4,
    armorType: "수정철",
    maneuver: 2,
    jump: 2,
    power: 60,
    fuel: 23,
    bridge: "표준",
    computer: "컴퓨터/5bis",
    sensors: "군용 (DM+0)",
    weapons: "이중 포탑(비어 있음) ×1",
    crew: "조종사, 항법사, 기관사",
    staterooms: "일반 객실 ×4",
    cargo: 11,
    tl: 12,
    durability: 40,
    maintenance: "Cr3079/월",
    price: "MCr36.9405",
    powerReq: { core: 20, maneuver: 20, jump: 20, sensors: 2, fuelProcessor: 2 },
    fuelConsumption: { jump1: 10, jump2: 20 },
    notes: "탐험·조사·연락 임무 표준 설계. 탐사 드론 ×10, 정비소, 에어/래프트 탑재. 연료 추출 장치 보유."
  },

  "seeker-mining": {
    name: "채굴 탐사선 (탐색자급)",
    type: "탐사선",
    hull: 100,
    hullShape: "유선형",
    armor: 4,
    armorType: "수정철",
    maneuver: 2,
    jump: 2,
    power: 60,
    fuel: 21,
    bridge: "표준",
    computer: "컴퓨터/5bis",
    sensors: "군용 (DM+0)",
    weapons: "이중 포탑(비어 있음) ×1",
    crew: "조종사, 항법사, 기관사",
    staterooms: "일반 객실 ×2",
    cargo: 30,
    tl: 12,
    durability: 40,
    maintenance: "Cr2859/월",
    price: "MCr34.3035",
    powerReq: { core: 20, maneuver: 20, jump: 20, sensors: 2, fuelProcessor: 1 },
    fuelConsumption: { jump1: 10, jump2: 20 },
    notes: "정찰선 변형. 화물칸 확장, 탐사 버기 탑재. 소행성 채굴 특화. 연료 탱크 축소."
  },

  "express-boat": {
    name: "급행 연락선 (X-보트)",
    type: "탐사선",
    hull: 100,
    hullShape: "구형",
    armor: 0,
    maneuver: 0,
    jump: 4,
    power: 20,
    fuel: 41,
    bridge: "표준",
    computer: "컴퓨터/15bis",
    sensors: "기본형",
    weapons: "없음",
    crew: "항법사/기관사",
    staterooms: "일반 객실 ×1",
    cargo: 2.75,
    tl: 12,
    durability: 40,
    maintenance: "Cr2842/월",
    price: "MCr34.1055",
    powerReq: { core: 20, jump: 40 },
    fuelConsumption: { jump4: 40 },
    notes: "제국 통신망의 핵심. 정찰대가 광대한 노선과 지원 거점을 유지. 우편 배포 장치(TL13) 탑재. 기동 드라이브 없음."
  },

  "survey-scout": {
    name: "조사 정찰선 (도노세프급)",
    type: "탐사선",
    hull: 400,
    hullShape: "분산 구조",
    armor: 0,
    maneuver: 3,
    jump: 3,
    power: 210,
    fuel: 124,
    bridge: "표준",
    computer: "컴퓨터/25",
    sensors: "개선형 (DM+1)",
    weapons: "없음",
    crew: "조종사, 항법사, 기관사×2, 의료, 과학자×5",
    staterooms: "일반 객실 ×10",
    cargo: 21,
    tl: 14,
    durability: 144,
    maintenance: "Cr13617/월",
    price: "MCr163.3995",
    powerReq: { core: 80, maneuver: 80, jump: 120, sensors: 4, fuelProcessor: 6 },
    fuelConsumption: { jump1: 40, jump2: 80, jump3: 120 },
    notes: "제국 성간 정찰대 내부 지역 재조사 전용. 모듈식 커터·에어/래프트×3 탑재. 고급 탐사 드론×20, 실험실×2 보유."
  },

  // =============================================
  // 상선
  // =============================================

  "free-trader": {
    name: "자유 무역선 (비오울프급)",
    type: "상선",
    hull: 200,
    hullShape: "유선형",
    armor: 2,
    armorType: "수정철",
    maneuver: 1,
    jump: 1,
    power: 75,
    fuel: 21,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "민간용 (DM-2)",
    weapons: "없음 (화물 크레인 탑재)",
    crew: "조종사, 항법사, 기관사, 접객원",
    staterooms: "일반 객실 ×10 / 냉동 침상 ×20",
    cargo: 80,
    tl: 12,
    durability: 80,
    maintenance: "Cr3854/월",
    price: "MCr46.242",
    powerReq: { core: 40, maneuver: 20, jump: 20, sensors: 1, fuelProcessor: 1, lowBerths: 2 },
    fuelConsumption: { jump1: 20 },
    notes: "전형적인 부정기 화물선. 화물 크레인·연료 정제기 탑재. 모험가들이 포탑과 무기를 추가하는 경우가 흔함."
  },

  "far-trader": {
    name: "원거리 무역선 (엠프레스 마라바급)",
    type: "상선",
    hull: 200,
    hullShape: "유선형",
    armor: 0,
    maneuver: 1,
    jump: 2,
    power: 90,
    fuel: 41,
    bridge: "표준",
    computer: "컴퓨터/5bis",
    sensors: "민간용 (DM-2)",
    weapons: "이중 포탑(빔 레이저) ×2",
    crew: "조종사/항법사, 기관사, 포격수×2, 접객원",
    staterooms: "일반 객실 ×10 / 냉동 침상 ×4",
    cargo: 57,
    tl: 12,
    durability: 80,
    maintenance: "Cr4513/월",
    price: "MCr54.1582",
    powerReq: { core: 40, maneuver: 20, jump: 40, sensors: 1, weapons: 18, fuelProcessor: 2, loadingBelt: 1, lowBerths: 1 },
    fuelConsumption: { jump1: 20, jump2: 40 },
    notes: "자유 무역선 변형. 더 큰 점프 드라이브로 더 먼 항성계 접근 가능. 에어/래프트 도킹 공간 탑재."
  },

  "subsidized-merchant": {
    name: "보조금 지급 상선 (뚱뚱한 무역선)",
    type: "상선",
    hull: 400,
    hullShape: "유선형",
    armor: 0,
    maneuver: 1,
    jump: 1,
    power: 135,
    fuel: 41,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "민간용 (DM-2)",
    weapons: "없음",
    crew: "조종사, 항법사, 기관사, 의료, 접객원",
    staterooms: "일반 객실 ×19 / 냉동 침상 ×9",
    cargo: 201,
    tl: 12,
    durability: 160,
    maintenance: "Cr6549/월",
    price: "MCr78.579",
    powerReq: { core: 80, maneuver: 40, jump: 40, sensors: 1 },
    fuelConsumption: { jump1: 40 },
    notes: "자유 무역선의 2배 크기. 거대한 화물칸이 핵심. 런치 도킹 공간 탑재. 성단 내 상업 수요 충족 설계."
  },

  "subsidized-liner": {
    name: "보조금 지급 여객선",
    type: "상선",
    hull: 600,
    hullShape: "일반형",
    armor: 0,
    maneuver: 1,
    jump: 3,
    power: 360,
    fuel: 183,
    bridge: "표준",
    computer: "컴퓨터/10bis",
    sensors: "민간용 (DM-2)",
    weapons: "없음",
    crew: "선장, 조종사×2, 항법사, 기관사×3, 정비, 의료, 접객원×10, 부관",
    staterooms: "고급 객실 ×4 / 일반 객실 ×30 / 이인실 ×10 / 냉동 침상 ×10",
    cargo: 60,
    tl: 12,
    durability: 240,
    maintenance: "Cr13968/월",
    price: "MCr167.6196",
    powerReq: { core: 120, maneuver: 60, jump: 180, sensors: 1, biosphere: 1, medBay: 1, lowBerths: 2 },
    fuelConsumption: { jump1: 60, jump2: 120, jump3: 180 },
    notes: "호화 시설 완비 여객선. 미식 주방·극장·수영장·온수욕조 탑재. 런치 도킹 공간 보유."
  },

  "safari-ship": {
    name: "사파리선 (애니멀급)",
    type: "상선",
    hull: 200,
    hullShape: "유선형",
    armor: 0,
    maneuver: 1,
    jump: 2,
    power: 105,
    fuel: 41,
    bridge: "표준",
    computer: "컴퓨터/5bis",
    sensors: "민간용 (DM-2)",
    weapons: "이중 포탑(비어 있음) ×1",
    crew: "조종사, 항법사, 기관사, 접객원, 의료",
    staterooms: "일반 객실 ×11",
    cargo: 13.2,
    tl: 12,
    durability: 80,
    maintenance: "Cr5103/월",
    price: "MCr61.227",
    powerReq: { core: 40, maneuver: 20, jump: 40, sensors: 1, fuelProcessor: 2, multiEnv: 1 },
    fuelConsumption: { jump1: 20, jump2: 40 },
    notes: "탐험·수렵 원정 전용 호화 유람선. 생물 표본 보관 탱크×2, 트로피 라운지 탑재. ATV·런치·에어/래프트 보유."
  },

  // =============================================
  // 특수선
  // =============================================

  "yacht": {
    name: "요트",
    type: "특수선",
    hull: 200,
    hullShape: "일반형",
    armor: 0,
    maneuver: 1,
    jump: 1,
    power: 90,
    fuel: 22,
    bridge: "표준",
    computer: "컴퓨터/5",
    sensors: "민간용 (DM-2)",
    weapons: "없음",
    crew: "조종사, 항법사, 기관사, 의료, 접객원",
    staterooms: "호화 객실 ×1 / 일반 객실 ×12",
    cargo: 16,
    tl: 12,
    durability: 80,
    maintenance: "Cr5211/월",
    price: "MCr62.5311",
    powerReq: { core: 40, maneuver: 20, jump: 20, sensors: 1, fuelProcessor: 1, trainingFacilities: 1 },
    fuelConsumption: { jump1: 20 },
    notes: "귀족의 전용 유람선. 미식 주방·극장·온수욕조·스튜디오·훈련 시설 탑재. 함재정·ATV·에어/래프트 보유."
  },

  "laboratory-ship": {
    name: "연구선 (Type L)",
    type: "특수선",
    hull: 360,
    hullShape: "분산 구조",
    armor: 0,
    maneuver: 2,
    jump: 2,
    power: 180,
    fuel: 82,
    bridge: "표준",
    computer: "컴퓨터/10",
    sensors: "개선형 (DM+1)",
    weapons: "없음",
    crew: "조종사, 항법사",
    staterooms: "일반 객실 ×20",
    cargo: 22,
    tl: 12,
    durability: 160,
    maintenance: "Cr9566/월",
    price: "MCr114.786",
    powerReq: { core: 72, maneuver: 80, jump: 80, sensors: 4 },
    fuelConsumption: { jump1: 40, jump2: 80 },
    notes: "과학자와 장비를 먼 지역으로 수송하는 연구 전용선. 실험실 80톤, 탐사 드론×15 탑재. 선체 회전식 중력 발생."
  },

  "fleet-courier": {
    name: "함대 연락선",
    type: "특수선",
    hull: 400,
    hullShape: "유선형",
    armor: 0,
    maneuver: 5,
    jump: 5,
    power: 380,
    fuel: 230,
    bridge: "소형 브리지",
    computer: "컴퓨터/30",
    sensors: "고급형",
    weapons: "삼중 포탑(빔 레이저) ×2 / 삼중 포탑(샌드캐스터) ×2",
    crew: "선장, 조종사×2, 기관사×2, 정비, 포격수×2",
    staterooms: "일반 객실 ×8",
    cargo: 5,
    tl: 15,
    durability: 160,
    maintenance: "Cr20569/월",
    price: "MCr246.825",
    powerReq: { core: 80, maneuver: 50, jump: 200, sensors: 6, weapons: 28, fuelProcessor: 56 },
    fuelConsumption: { jump1: 40, jump2: 80, jump3: 120, jump4: 160, jump5: 200 },
    notes: "함대 사령관의 명령·정보 전달 전용. Jump-5, M-5 고성능. 방어 무장만 탑재해 전투 회피 우선."
  },

  // =============================================
  // 군함
  // =============================================

  "close-escort": {
    name: "근접 호위함 (가제트급)",
    type: "군함",
    hull: 400,
    hullShape: "밀집 구조",
    armor: 3,
    armorType: "결합 초고밀도",
    maneuver: 5,
    jump: 5,
    power: 570,
    fuel: 130,
    bridge: "소형 브리지",
    computer: "컴퓨터/20bis",
    sensors: "군용 (DM+0)",
    weapons: "입자 바벳 ×2 / 삼중 포탑(빔 레이저) ×2",
    crew: "선장, 조종사×3, 항법사, 기관사×4, 정비, 의료, 포격수×8, 부관",
    staterooms: "일반 객실 ×5 / 막사 ×12",
    cargo: 23.8,
    tl: 14,
    durability: 160,
    maintenance: "Cr15720/월",
    price: "MCr188.6373",
    powerReq: { core: 80, maneuver: 200, jump: 260, sensors: 2, weapons: 56, fuelProcessor: 10, medBay: 1 },
    fuelConsumption: { jump3: 120, jump4: 160, jump5: 200 },
    notes: "구식이지만 다수 현역. 해적 대응·대기권 추격 가능. 군용 소형정 탑재. 증설 탱크로 Jump-5 가능."
  },

  "patrol-corvette": {
    name: "초계함 (Type T)",
    type: "군함",
    hull: 400,
    hullShape: "유선형",
    armor: 4,
    armorType: "수정철",
    maneuver: 4,
    jump: 3,
    power: 300,
    fuel: 122,
    bridge: "표준",
    computer: "컴퓨터/15",
    sensors: "군용 (DM+0)",
    weapons: "삼중 포탑(펄스 레이저) ×2 / 삼중 포탑(미사일 발사대) ×2",
    crew: "조종사, 항법사, 기관사×2, 의료, 포격수×4, 해병×8",
    staterooms: "일반 객실 ×12 / 냉동 침상 ×4",
    cargo: 43,
    tl: 12,
    durability: 160,
    maintenance: "Cr14870/월",
    price: "MCr178.434",
    powerReq: { core: 80, maneuver: 160, jump: 120, sensors: 2, weapons: 28, fuelProcessor: 4 },
    fuelConsumption: { jump1: 40, jump2: 80, jump3: 120 },
    notes: "밀수·해적 감시, 항성계 방어용. 함재정·G/캐리어 탑재. 유선형 선체로 대기권·행성 표면 추격 가능."
  },

  "mercenary-cruiser": {
    name: "용병 순양함 (Type C)",
    type: "군함",
    hull: 800,
    hullShape: "구형",
    armor: 4,
    armorType: "수정철",
    maneuver: 3,
    jump: 3,
    power: 750,
    fuel: 252,
    bridge: "표준",
    computer: "컴퓨터/25fib",
    sensors: "군용 (DM+0)",
    weapons: "삼중 포탑 ×8",
    crew: "조종사, 항법사, 기관사×3, 의료, 포격수×4, 해병×8",
    staterooms: "일반 객실 ×25",
    cargo: 72,
    tl: 12,
    durability: 320,
    maintenance: "Cr24974/월",
    price: "MCr299.6946",
    powerReq: { core: 160, maneuver: 240, jump: 240, sensors: 2, weapons: 8 },
    fuelConsumption: { jump1: 80, jump2: 160, jump3: 240 },
    notes: "소규모 전투 부대 수송 특화. 모듈식 커터×2, 수리 드론 탑재. 800톤급 (High Guard 미수록, 코어 룰북 기준)."
  },

  "system-defence-boat-200": {
    name: "항성계 방어정 200t",
    type: "군함",
    hull: 200,
    hullShape: "일반형",
    armor: 13,
    armorType: "수정철",
    maneuver: 9,
    jump: 0,
    power: 240,
    fuel: 6,
    bridge: "홀로그래픽 브리지",
    computer: "컴퓨터/35",
    sensors: "개선형 / 대응책 장치",
    weapons: "삼중 포탑(빔 레이저) ×1 / 삼중 포탑(미사일 발사대) ×1",
    crew: "선장, 조종사×3, 기관사, 정비, 포격수×4, 행정관, 의료, 부관",
    staterooms: "일반 객실 ×15",
    cargo: 14.6,
    tl: 15,
    durability: 88,
    maintenance: "Cr11035/월",
    price: "MCr132.417",
    powerReq: { core: 40, maneuver: 180, sensors: 5, weapons: 14, medBay: 1, fuelProcessor: 1 },
    notes: "TL15 강화 방어정. 점프 드라이브 없음. 방사선 차폐·수리 드론 탑재. 미사일 240발 적재."
  },

  "system-defence-boat-400": {
    name: "항성계 방어정 400t (드래곤급)",
    type: "군함",
    hull: 400,
    hullShape: "일반형",
    armor: 13,
    armorType: "수정철",
    maneuver: 7,
    jump: 0,
    power: 450,
    fuel: 12,
    bridge: "홀로그래픽 브리지",
    computer: "컴퓨터/25fib (백업: 컴퓨터/20fib)",
    sensors: "개선형 / 대응책·확장 배열·신호 처리",
    weapons: "소형 미사일 베이 ×1 / 입자 바벳 ×2 / 점방어 레이저 배터리(II형) ×1",
    crew: "선장, 조종사×3, 항법사, 기관사×2, 정비, 의료, 포격수×6, 감지사×3, 부관",
    staterooms: "일반 객실 ×10",
    cargo: 18,
    tl: 12,
    durability: 176,
    maintenance: "Cr23119/월",
    price: "MCr277.425",
    powerReq: { core: 80, maneuver: 280, sensors: 15, weapons: 55, biosphere: 4, medBay: 1 },
    notes: "점프 드라이브 없음. 방사선 차폐, 생물권, 수리 드론·훈련 시설·정비소 탑재. 미사일 480발 적재."
  }
};

export const SHIP_TYPES = Object.entries(SHIP_DATA).map(([id, data]) => ({
  id,
  name: data.name,
  type: data.type
}));

// 카테고리별 그룹
export const SHIP_CATEGORIES = {
  "소형정": Object.entries(SHIP_DATA).filter(([,d]) => d.type === "소형정").map(([id,d]) => ({ id, name: d.name })),
  "탐사선": Object.entries(SHIP_DATA).filter(([,d]) => d.type === "탐사선").map(([id,d]) => ({ id, name: d.name })),
  "상선":   Object.entries(SHIP_DATA).filter(([,d]) => d.type === "상선").map(([id,d]) => ({ id, name: d.name })),
  "특수선": Object.entries(SHIP_DATA).filter(([,d]) => d.type === "특수선").map(([id,d]) => ({ id, name: d.name })),
  "군함":   Object.entries(SHIP_DATA).filter(([,d]) => d.type === "군함").map(([id,d]) => ({ id, name: d.name })),
};
